/**
 * fallow install helper for the `devkit init` wizard. fallow is the free static-analysis
 * layer (dead-code, dupes, complexity health) the devkit gate set can lean on. This module
 * OWNS getting fallow onto a consumer's machine + wiring its OWN self-maintaining hook —
 * it deliberately does NOT replicate frink's husky-specific layer (the `.claude/hooks/
 * fallow-gate.sh` PreToolUse hook + `fallow-staged-filter.mjs` staged-diff scoping). That
 * frink customisation is re-generated by `fallow hooks install` and then hand-patched; a
 * fresh consumer just gets fallow's stock hook via `fallow hooks install`.
 *
 * Everything here is FAIL-OPEN: a missing package manager, an offline machine, or fallow
 * not being installed must never throw — the wizard keeps going and prints the manual
 * fallback. dryRun prints every external command and runs none of them.
 */

import { spawnSync } from 'node:child_process';
import { chmodSync, existsSync, readFileSync, realpathSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { readJson, writeIfAbsent } from '../fs-helpers.mts';

/**
 * Pinned fallow version. NEVER @latest — a floating tag makes the gate non-deterministic
 * and can drift below FALLOW_GATE_MIN_VERSION. 3.6.0 sits well above the default floor
 * (2.46.0), so a pinned install always satisfies the gate's version check.
 *
 * The floor here is >=3.4.2, not just "newer is nicer". Through 2.x, `fallow audit`
 * materialised its comparison base as a REGISTERED git worktree and its cleanup was not
 * scoped to the entry it owned — so a long-running audit (a devkit ship's gate chain runs
 * for minutes) could reset the SHIP worktree's HEAD to the audit's own base, and the
 * commit then died on its finalize ref-update with
 * `fatal: cannot lock ref 'HEAD': is at <base> but expected <ship base>`, having passed
 * every gate. fallow 3.4.2 unregisters the snapshot immediately and restricts "Git
 * administration cleanup ... to the current repository's verified worktree entry"; 3.6.0
 * holds the reuse lock for the audit lifetime so a concurrent cleanup or a different-base
 * rebuild cannot pull files out from under a running audit. 3.4.2 also auto-deregisters
 * the worktree entries leaked by earlier versions on the next audit.
 *
 * fallow 3.0.0 is a platform milestone, NOT a breaking change: CLI flags, config, and the
 * `audit --format json` contract this repo parses (gate-engine/fallow/staged-filter.mts)
 * are unchanged across the major.
 */
export const FALLOW_PINNED_VERSION = '3.6.0';

// The three per-analysis baselines `fallow audit` consumes (--dead-code-baseline etc.).
// Each maps a sub-analysis save command to its file under fallow-baselines/.
const BASELINES = [
  { cmd: 'dead-code', file: 'dead-code.json' },
  { cmd: 'health', file: 'health.json' },
  { cmd: 'dupes', file: 'dupes.json' },
];

// Shared shape for every command helper's options object (the destructured `opts` arg).
interface FallowCommandOptions {
  cwd?: string;
  dryRun?: boolean;
}

// `run`'s superset: adds `capture` (piped+utf8 for version probes vs inherited stdio).
interface RunOptions extends FallowCommandOptions {
  capture?: boolean;
}

// A single spawn's normalised result: exit status (null = spawn error, e.g. ENOENT) + captured stdout.
interface RunResult {
  status: number | null;
  stdout: string;
}

/**
 * Single spawn seam. Every external command in this module funnels through here so dryRun
 * print-and-skip and the test mock have ONE place to intercept. Inherits stdio by default
 * so install progress/output is visible; `capture` flips to piped+utf8 for version probes.
 * Never throws — a spawn error (ENOENT for a missing binary) comes back as status:null.
 */
function run(
  cmd: string,
  args: string[],
  { cwd, dryRun, capture = false }: RunOptions = {},
): RunResult {
  if (dryRun) {
    console.log(`[dry-run] ${cmd} ${args.join(' ')}`);
    return { status: 0, stdout: '' };
  }
  const r = spawnSync(cmd, args, {
    cwd,
    encoding: 'utf8',
    stdio: capture ? ['ignore', 'pipe', 'pipe'] : 'inherit',
  });
  return { status: r.error ? null : r.status, stdout: r.stdout ?? '' };
}

// Match a "fallow X.Y.Z" probe line, capturing the bare version.
const VERSION_RE = /fallow\s+(\d+\.\d+\.\d+\S*)/;

// Parse a version probe into the bare version, or null if it didn't match.
function parseVersion(stdout: string): string | null {
  const m = VERSION_RE.exec(stdout);
  return m ? m[1] : null;
}

/**
 * Is fallow reachable? Try the binary on PATH first, then `npx --no-install` (uses an
 * already-installed local copy without a network fetch). Never throws.
 *
 */
export function detectFallow({ cwd }: { cwd?: string } = {}): {
  available: boolean;
  version: string | null;
} {
  const probes: [string, string[]][] = [
    ['fallow', ['--version']],
    ['npx', ['--no-install', 'fallow', '--version']],
  ];
  for (const [cmd, args] of probes) {
    const { status, stdout } = run(cmd, args, { cwd, capture: true });
    const version = parseVersion(stdout);
    if (status === 0 && version) return { available: true, version };
  }
  return { available: false, version: null };
}

// The package-manager attempts, in priority order. cargo's crate is `fallow-cli` but the
// installed binary is `fallow` — pin the crate by --version, not an @-suffix.
function installAttempts() {
  return [
    { method: 'bun', cmd: 'bun', args: ['add', '-g', `fallow@${FALLOW_PINNED_VERSION}`] },
    { method: 'npm', cmd: 'npm', args: ['install', '-g', `fallow@${FALLOW_PINNED_VERSION}`] },
    {
      method: 'cargo',
      cmd: 'cargo',
      args: ['install', 'fallow-cli', '--version', FALLOW_PINNED_VERSION],
    },
  ];
}

// The exact manual commands to print when every automated attempt misses. No brew tap and
// no curl|sh installer exist for fallow — do not invent one.
function printManualSteps() {
  console.log('fallow could not be installed automatically. Install it manually with one of:');
  for (const a of installAttempts()) {
    console.log(`  ${a.cmd} ${a.args.join(' ')}`);
  }
}

/**
 * Install fallow, trying bun → npm → cargo and stopping at the first success. On a total
 * miss it prints the manual commands and returns ok:false — NEVER throws.
 *
 */
export function installFallow({ cwd, dryRun }: FallowCommandOptions = {}): {
  ok: boolean;
  method: string | null;
  message: string;
} {
  for (const a of installAttempts()) {
    const { status } = run(a.cmd, a.args, { cwd, dryRun });
    if (status === 0) {
      return {
        ok: true,
        method: a.method,
        message: `installed fallow@${FALLOW_PINNED_VERSION} via ${a.method}`,
      };
    }
  }
  printManualSteps();
  return { ok: false, method: null, message: 'no package manager could install fallow' };
}

/**
 * Idempotently ensure `.fallow/` is gitignored (fallow's local cache dir). Appends the
 * line only when absent; creates .gitignore if the repo has none.
 *
 */
export function ensureFallowGitignore({ cwd, dryRun }: FallowCommandOptions = {}): void {
  const path = join(cwd ?? process.cwd(), '.gitignore');
  const line = '.fallow/';
  const existing = existsSync(path) ? readFileSync(path, 'utf8') : '';
  if (existing.split('\n').includes(line)) return;
  if (dryRun) {
    console.log(`[dry-run] append "${line}" to ${path}`);
    return;
  }
  if (!existing) {
    writeIfAbsent(path, `${line}\n`);
    return;
  }
  writeIfAbsent(path, `${existing}${existing.endsWith('\n') ? '' : '\n'}${line}\n`, {
    force: true,
  });
}

/**
 * Wire fallow's OWN self-maintaining hook via `fallow hooks install --target <git|agent>`.
 * This is fallow's hook, not devkit's gate — we do NOT hand-write a husky line for it.
 * Fail-open: a missing/erroring fallow returns ok:false, never throws.
 *
 */
export function wireFallowGate({
  cwd,
  dryRun,
  target = 'git',
}: FallowCommandOptions & { target?: string } = {}): { ok: boolean } {
  const { status } = run('fallow', ['hooks', 'install', '--target', target], { cwd, dryRun });
  return { ok: status === 0 };
}

/**
 * Wire ALL of fallow's own hooks for a consumer, across every surface devkit supports.
 *
 * devkit installs fallow's hooks rather than shipping a gate of its own: `fallow audit` already
 * defaults to `--gate new-only` (only findings the changeset introduces fail) and takes
 * `--diff-file`/`--diff-stdin` for exact scoping, so a devkit-authored gate would reimplement
 * fallow's attribution and then drift from it. fallow regenerates its script on every install;
 * devkit only wires it and mirrors it onto Cursor, which fallow's installer does not write.
 *
 * `--target git` is the husky-managed pre-commit hook; `--target agent` is the Claude/Codex gate.
 * Fail-open throughout: `ok` reports the git hook (what the baseline step keys off), and `log`
 * carries the caller's progress lines so the wizard stays a two-liner.
 */
export function wireFallowHooks({ cwd, dryRun }: FallowCommandOptions = {}): {
  ok: boolean;
  log: string[];
} {
  const log: string[] = [];
  const git = wireFallowGate({ cwd, dryRun, target: 'git' });
  log.push(`${git.ok ? '✓ wired' : '! could not wire'} fallow git hook`);
  const agent = wireFallowGate({ cwd, dryRun, target: 'agent' });
  log.push(`${agent.ok ? '✓ wired' : '! could not wire'} fallow agent hook`);
  if (agent.ok && mirrorFallowAgentHookToCursor({ cwd, dryRun }).ok) {
    log.push(`${dryRun ? '[dry-run] mirror' : '✓ mirrored'} fallow agent hook → .cursor`);
  }
  return { ok: git.ok, log };
}

// The slice of `.cursor/hooks.json` this mirror touches.
interface CursorHooksDoc {
  hooks?: Record<string, { command: string }[]>;
}

/**
 * Mirror fallow's generated AGENT hook onto the Cursor surface.
 *
 * `fallow hooks install --target agent` writes the CLAUDE surface only (`.claude/settings.json`
 * plus `.claude/hooks/fallow-gate.sh`, and an AGENTS.md block for Codex). devkit also targets
 * Cursor, so copy the generated script there and register it under `beforeShellExecution` — the
 * same PreToolUse+Bash → Cursor mapping install-hooks uses. The script is fallow's, regenerated by
 * fallow on every install; devkit only wires and mirrors it, never edits it.
 *
 * Fail-open: returns ok:false when fallow's script isn't there, never throws.
 */
export function mirrorFallowAgentHookToCursor({
  cwd = process.cwd(),
  dryRun = false,
}: FallowCommandOptions = {}): { ok: boolean } {
  const src = join(cwd, '.claude', 'hooks', 'fallow-gate.sh');
  if (!existsSync(src)) return { ok: false };
  if (dryRun) return { ok: true };
  const dest = join(cwd, '.cursor', 'hooks', 'fallow-gate.sh');
  writeIfAbsent(dest, readFileSync(src), { force: true });
  chmodSync(dest, 0o755);

  const hooksPath = join(cwd, '.cursor', 'hooks.json');
  const doc: CursorHooksDoc = (readJson(hooksPath) as CursorHooksDoc | null) ?? {};
  doc.hooks ??= {};
  doc.hooks.beforeShellExecution ??= [];
  const command = '.cursor/hooks/fallow-gate.sh';
  // Idempotent: a re-run (init, upgrade) must not stack duplicate entries.
  if (!doc.hooks.beforeShellExecution.some((hook) => hook.command === command)) {
    doc.hooks.beforeShellExecution.push({ command });
  }
  writeIfAbsent(hooksPath, `${JSON.stringify(doc, null, 2)}\n`, { force: true });
  return { ok: true };
}

/**
 * Save the three per-analysis baselines into fallow-baselines/ so `fallow audit` only
 * fails on genuinely NEW issues (pre-existing debt is grandfathered). Fail-open per save.
 * Only the integrator calls this — and only when the gate was wired AND the repo has debt.
 *
 */
export function saveFallowBaselines({ cwd, dryRun }: FallowCommandOptions = {}): { ok: boolean } {
  let ok = true;
  for (const { cmd, file } of BASELINES) {
    const target = join('fallow-baselines', file);
    // capture (not inherit): the baseline file is written regardless, and we DON'T want fallow's
    // full health/dupes/dead-code report flooding the install terminal — the caller prints a
    // one-line "saved baselines" summary instead.
    const { status } = run('fallow', [cmd, '--save-baseline', target], {
      cwd,
      dryRun,
      capture: true,
    });
    if (status !== 0) ok = false;
  }
  return { ok };
}

// CLI smoke entry: `node install-fallow.mjs [detect|install|gate|baselines]`. Helps verify
// the helper by hand without the wizard.
if (process.argv[1] && import.meta.url === pathToFileURL(realpathSync(process.argv[1])).href) {
  const sub = process.argv[2] ?? 'detect';
  const cwd = process.cwd();
  if (sub === 'detect') console.log(JSON.stringify(detectFallow({ cwd })));
  else if (sub === 'install') console.log(JSON.stringify(installFallow({ cwd })));
  else if (sub === 'gate') console.log(JSON.stringify(wireFallowGate({ cwd })));
  else if (sub === 'baselines') console.log(JSON.stringify(saveFallowBaselines({ cwd })));
  else console.error(`unknown subcommand: ${sub}`);
}
